### ISSUE TITLE
[Question] how to check scopes and roles for the same route

### ISSUE THREAD

**Issue by copdips** [Intility/fastapi-azure-auth#118]
**Describe the bug**
I have a route that may be called by user (by the Authorize button from openapi) or by SPN (who generates access token in advance before calling fastapi).

From the examples given in the doc, I can whether check the scopes in case of users (auth code flow), whether check the roles in case of SPN (client crendentials flow). But I cannot figure out how to get them together, as my route shoud accept both cases. I could write some control inside of route, but I would like to get it done at Depends level.

**Comment by copdips** [comment]
@JonasKs 

I want to use scopes to control permissions for users:
![image](https://user-images.githubusercontent.com/13083856/227331390-6fe9098d-56b3-4b7d-a74f-2c13845b7f21.png)

and use roles to control permissions to SPN:
![image](https://user-images.githubusercontent.com/13083856/227331743-e4a013e3-9e5c-4d37-8d85-120496315eee.png)

From the fastapi-azure-auth doc, I can control one of them, I would like to how to control both of them in fastapi, as my route will accept both users and SPNs as client.

**Comment by copdips** [comment]
to control both scopes and roles inside the route is simply manually decode the access token , and checks the scopes or roles based the token is for user or spn, but I don't think this an elegant way to handle the permission, it would nice if we can do it at Depends or decorator level.

**Comment by bmoore** [comment]
My strategy was to write a function that takes a scope or role name as a parameter. That function returns a callable that takes the user object as a parameter and checks if scopes or roles match the initial args. Then you can call that in the dependency part of the route.

**Comment by bmoore** [comment]
If I weren't travelling I could send you a concrete example.

**Comment by JonasKs** [comment]
I believe [this](https://intility.github.io/fastapi-azure-auth/multi-tenant/accept_specific_tenants_only) could solve your use case?

**Comment by copdips** [comment]
@bmoore , works like a charm, thanks a lot

**Comment by JonasKs** [comment]
> Sorry, I cannot figure out the solution with your link, I expected to have something like:
> 
> 
> 
> ```Python
> 
> dependencies=[Security(azure_scheme, scopes=[scope1, scope2], roles=[role1, role2])]
> 
> ```

I'll have to investigate this, but I like the idea. 

I've asked our identity department on how the combination of roles and scopes really are intended to be used together, since personally I only use roles with a default scope.

I'll update here when I hear back. 

Glad you solved it in the mean time 😊 Thanks @bmoore !

**Comment by RickardCardell** [comment]
I also had some trouble with this combination of auth methods on the same endpoint.  
I'm just sharing my findings so far :)

I tried the [demo_project](https://github.com/intility/fastapi-azure-auth/tree/main/demo_project) both from the OpenAPI UI and using app tokens in the guide [Calling your APIs from Python](https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python).

I took me a while to understand why it didn't work with app-tokens until I saw that it's configured to validate the scope [here](https://github.com/intility/fastapi-azure-auth/blob/main/demo_project/main.py#L54):
```
app.include_router(
    api_router_azure_auth,
    prefix=settings.API_V1_STR,
    dependencies=[Security(azure_scheme, scopes=['user_impersonation'])],
```
It seems that using `Security.scopes` prevents access for non-delegated auth methods.
The reason is in [here](https://github.com/intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/auth.py#L184-L192), where scopes are checked for all type of calls

One perhaps naive solution could be to have a if-statement to only check calls for delegated auth methods:
```
            # Get the type of auth method and check if it's a public client using pkce or not.
            # https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference

            is_public_client = claims.get("azpacr") == "0"
            if is_public_client:
                for scope in security_scopes.scopes:
```

However, maybe that will have security implications for current usages that only want to allow public clients and disallow the other auth methods implicitly?

Another idea is to not use `Security.scopes` but instead make a separate class, with inspiration from @bmoore:

```
class ValidateUserScopes:
    def __init__(self, scopes: List[str]) -> None:
        self.scopes = set(scopes)

    async def __call__(self, user: User = Depends(azure_scheme)) -> None:
        """
        Check user scopes from the jwt token. Supports only v2 api-version.
        Other auth methods are let through.
        """
        # valid authentication methods of the client
        if user.azpacr not in ["0", "1", "2"]:
            raise ValueError(f"Unexpected auth type: '{user.azpacr}'")

        # Validate scopes. Only relevant for real users. Not for app tokens ("1") or certificates ("2")
        # https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference
        if user.azpacr == "0":
            for scope in self.scopes:
                token_scopes = user.scp
                if scope not in token_scopes:
                    raise ForbiddenHttp(f"Required scope missing: '{scope}'. Scopes in token: '{token_scopes}'")
```

E.g. in [demo_project/main.py](https://github.com/intility/fastapi-azure-auth/blob/main/demo_project/main.py#L54), instead of
```
app.include_router(
    api_router_azure_auth,
    prefix=settings.API_V1_STR,
    dependencies=[Security(azure_scheme, scopes=['user_impersonation'])],
)
```
use a separate dependency
```
app.include_router(
    api_router_azure_auth,
    prefix=settings.API_V1_STR,
    dependencies=[
        Security(azure_scheme),
        Security(ValidateUserScopes(scopes=["user_impersonation"])),
    ],
)
```
It can be used on routers and endpoints as well of course.  
Note that further checks might be needed to check for [role-memberships](https://intility.github.io/fastapi-azure-auth/usage-and-faq/locking_down_on_roles) etc.
