### ISSUE TITLE
get JWT token after validation 

### ISSUE THREAD

**Issue by mohsspark829** [Intility/fastapi-azure-auth#127]
Hi there, 

Thank you for preparing this amazing package which is actually a life saver. I have a bit of a complex situation which I would greatly appreciate any help. We have keycloak in our K8s which is connected to AAD. Our main goal is enabling SSO in swagger/API by using keycloak, however as I could not find any suitable library/example to achieve this goal we are using your library. Our UI is getting the token from keycloak and then pass it to FastAPI and if the token is valid, then our FastAPI send the response.

Now, I am using fastapi-azure-auth library to validate users on the swagger and it works fine. With Postman there is no issue as well, but when I get the generated token from keycloak (actually at the UI) and use the postman to send a request to the below endpoint by putting the token that I received from the keycloak I get the below error.

@app.get("/azure_scheme_keycloak/")
async def azure_scheme_keycloak_ep(request:Request,token: str = Depends(azure_scheme)):
    print('token issssss:',token)
    print("request:",request)
    return {"message": "Hello World from azure scheme and keycloak"}

Error:
{
  "detail": "Unable to verify token, no signing keys found"
}

which actually make sense as AAD does not know anything about the token which has been generated by the keycloak.

To overcome this problem,

_I am thinking of getting the JWT token from the endpoint and if the response from AAD is invalid then pass this token to keycloak and authenticate the request, but not sure whether this is possible or there is a better way to do it, or how to do it properly. If you believe this question should not be here I completely understand, but I really appreciate any help._

**Comment by JonasKs** [comment]
Hey 😊

I'm not familiar with Keycloak, but as far as I know, it is an Identity Provider, right? So essentially you'd like to have Azure AD _and_ Keycloak work for your APIs?

You can have multiple dependencies, using the `auto_error=False` flag. See the example repository [here](https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/dependencies.py#L93). How ever, the Keycloak token must also be validated. 

I'm not sure how you plan to do this, but there might be a generic oauth2 library out here you could use?

**Comment by mohsspark829** [comment]
Hey Jonas, Yes , KeyCloak is an IP which can use AAD. I will have a look at GitHub example. Thanks for this. I had some look around the existing libraries for SAML and Open ID but was not able to find something that I could understand/suitable for our use case, although I may give it another shot now that I now how to do thing in AAD, Thanks a lot for your documentation! It is really helpful especially the explanation about AAD.

**Comment by JonasKs** [comment]
No problem. 😊 This package aim to solve the Azure flavor of oauth2/OIDC, since they extend the RFCs quite extensively (as an example, there is no RFC for multi-tenant OIDC, whatever Azure does may be totally different from some other IDP). Unfortunately, that means we _only_ support AzureAD, and not Keycloak. How ever, as shown in the example, you can easily have multiple libraries if you'd like. 😊 (requires them to support `auto_error=False`. 

I'm glad you feel like you know more now, though!  
If you want some more resources, I've also written a blog article about OIDC [here](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application).  

For now, I'll close this issue, but I'll still get notified of any replies if you have further questions 😊

**Comment by mohsspark829** [comment]
Thanks Jonas for the multi-depdency example, I was able to implement a similar approach by the below code:

async def get_current_user(token: str = Depends(oauth2_scheme),azure_auth: Optional[User] = Depends(azure_scheme)):
    if azure_auth:
        return azure_auth.name
    else:
        check with the keycloak....


so now, I am able to use both AAD and keycloak side by side.  Thanks again and have a great day.

**Comment by JonasKs** [comment]
You're welcome 😊

**Comment by JonasKs** [comment]
Hi😊 yeah, you’re correct, that will work the same. I will consider rewriting it, and rather have a section on how to implement a SPA using PKCE if people think that’s better. 

I initially did it with two appregs because:  
1) it works the same
2) it teaches how to implement any application, and how they can talk to the backend. React frontend? No problem, do the same as before. Mobile app? No problem, do the same. 

One of the hardships of maintaining and helping people using my Django-auth-ADFS package has been how to actually integrate other apps, since these things were not documented with intent.

**Comment by mohsspark829** [comment]
Yes, I though the same, for the educational purpose, but just wanted to be sure that there is no other issue (as I am not expert in Azure and Security). However, thanks once again for the nice documentation and all the helps and times you spend to respond to me (and others). Wish you all the best and thanks a million!

**Comment by JonasKs** [comment]
No other issue - just as safe! I'll think about changing it, and rather have a section on how to integrate with it😊 

Thanks for the feedback and kind words 😊

**Comment by mohsspark829** [comment]
I am happy to write the documentation in a word document and email it to
you. In this way, you may spend less time on it, hopefully:). I will try to
prepare for it by the end of the day.
