### ISSUE TITLE
[Bug/Question]

### ISSUE THREAD

**Issue by Ciscko** [Intility/fastapi-azure-auth#173]
**Describe the bug**

First, thank you Jonas for the work you put in building this library.

I have followed the documentation and I'm able to get to the authorized page. 
![Auth](https://github.com/Intility/fastapi-azure-auth/assets/32708966/0d05b385-b936-4a5a-bd2b-fe33c4032819)

The problem comes when I try to call the protected endpoint. I get status 401 and message below even when using the same admin account that I used to do the Azure Configuration.
![image](https://github.com/Intility/fastapi-azure-auth/assets/32708966/05cf3e8b-f28a-4ea1-9165-3997e46ce370)

**To Reproduce**
I used the code exactly as provided in the documentation.

**Stack trace**

**Your configuration**
Azure is configured as instructed in the documentation.

**Comment by JonasKs** [comment]
If this is a Single-tenant app (no external users), you're being blocked because you're a [guest user](https://intility.github.io/fastapi-azure-auth/usage-and-faq/guest_users).   

You might also misunderstand which tenant type you should use. You might want to use [B2C](https://intility.github.io/fastapi-azure-auth/b2c/azure_setup) instead.

**Comment by Ciscko** [comment]
Thank you Jonas,

I have sorted it out!

You are a Star!
