### ISSUE TITLE
[BUG/Question] Example use cases for scopes

### ISSUE THREAD

**Issue by dom-gunstone** [Intility/fastapi-azure-auth#186]
Hi, 

Firstly, thanks for the work on this project. It's going to be really useful.

Would you be able to describe some examples for where and why you would use scopes, please? The documentation describes the creation of a `user_impersonation` scope that allows users to consent to the application using the API as the user, but I can't think of any more use cases.

The Entra docs are particularly confusing on scopes...

Thanks.

**Comment by dom-gunstone** [comment]
Thanks @bmoore, that's really helpful. I think I'm struggling to apply the scope mechanism to a "real world" FastAPI example.

This is probably a terrible example (this is all in my head), but, if I had a Book API with basic CRUD operations I would create roles in Entra e.g.:
- Reader
- Editor
- Admin

I can then give roles to users/groups etc. and have the FastAPI app check for roles.

For scopes would I define them like this?:
- Books.Read - _Allow the app to read books_
- Books.ReadWrite - _Allow the app to read and write books_
- Books.Write - _All the app to write books_

Is this correct?: The scopes define what the user has consented the application to do on their behalf. The roles are what "Entra admins" have decided a user has access to. Scopes are a subset of permissions, a user may have many but only allow one.

Does using scopes in the Book API example even make sense? Consenting to user personal information intuitively makes sense, but consenting to reading/writing book information doesn't since it's not necessarily the user's data?

**Comment by bmoore** [comment]
Quick response, detail to follow. User roles can be seen more like application roles where it provides RBAC authorization to resources at large. Scopes would likely have more specific names, if you wanted to grant granular access (read vs readwrite) but the difference, from my understanding, comes down to checking whether the user is authorized to access a given resource.

Consider a Document. If a client makes a read call to an API's document endpoint on behalf of the user, the API checks roles and scopes. The API can(read should) check whether a Document scope exists on the token before getting documents. If there's a document.read scope, then when processing the request, the API should make sure the user owns (or otherwise has) access to the document by some policy you define.

Part of that policy could be checking for a user role, maybe something like Document Admin that allows the user to read and write all documents. But on the case that their role is just User, the API would check for owner / share rights.

I hope that's a decent example. Just spinning from the top of my head

**Comment by dom-gunstone** [comment]
That's great information, thank you! It's much clearer in my head now.

I think the docs example through me off a bit with `user_impersonation`. In you opinion, is there a need for this if I have more granular scopes?

**Comment by sstorey-bma** [comment]
Is it possible to use the library to authenticate, BUT then inject the scopes allowed for an user (post authentication from Azure). If possible want to manage user roles/groups/scopes outside of Entra (and stored within our application), but authenticate the user with Entra. Any thoughts?

**Comment by JonasKs** [comment]
Thank you @bmoore for the follow up here! 

In general, most applications does not need to use scopes, and roles will be sufficient. When the use case for scopes is there, it will most of the time be pretty obvious, and the OBO flow bmoore explains is one of them. 

@sstorey-bma , yes, this is absolutely possible, and require you to use `auto_error=False`. I haven't really documented this use-case, but the [setting exist](https://intility.github.io/fastapi-azure-auth/settings/single_tenant#auto_error-bool), which allow you to chain dependencies, as shown in the [demo project](https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/dependencies.py#L93). It basically works by saying "do not raise an exception when the user can't be verified". In order to achieve what you would like, you could do something like this:

- A dependency checking for azure auth
  - if it returns None the user isn't authenticated
  - if it returns a user object, the user is authenticated. You can then look up the user in your database, and check for extra permissions.
